// src/components/delima/testimonials.tsx
// Delima Realtors Platform 2.0 — Client testimonials carousel (classic)
// Owner: orchestrator (classic redesign).
// One large serif quote at a time, prev/next controls, "01 / 06" pagination —
// the timeless estate-agency pattern. Auto-advances every 9s, pauses on hover.
'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowRight, ChevronLeft, ChevronRight } from 'lucide-react'
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar'
import { Button } from '@/components/ui/button'
import { useAppStore } from '@/lib/store'
import { formatKes, formatDate } from '@/lib/format'
import { TESTIMONIALS, type Testimonial } from '@/lib/testimonials-data'
import { cn } from '@/lib/utils'

const AUTOPLAY_MS = 9000

function initialsFor(name: string): string {
  return (
    name
      .split(/[\s&]+/)
      .filter(Boolean)
      .slice(0, 2)
      .map(p => p[0]?.toUpperCase() ?? '')
      .join('') || '·'
  )
}

/* ------------------------------------------------------------------ */
/* Star row — inline SVG, decorative stars inside a labelled container */
/* ------------------------------------------------------------------ */

function StarRow() {
  return (
    <div className="flex items-center justify-center gap-1" role="img" aria-label="5 out of 5 stars">
      {Array.from({ length: 5 }).map((_, i) => (
        <svg key={i} viewBox="0 0 24 24" aria-hidden="true" className="size-4 fill-gold text-gold">
          <path d="M12 2.2l2.95 6.68 7.05.6-5.3 4.85 1.6 7.15L12 17.8 5.7 21.45l1.6-7.15L2 9.3l7.05-.6z" />
        </svg>
      ))}
    </div>
  )
}

/* ------------------------------------------------------------------ */
/* Classic carousel                                                    */
/* ------------------------------------------------------------------ */

export default function Testimonials() {
  const setView = useAppStore(s => s.setView)
  const [index, setIndex] = useState(0)
  const [paused, setPaused] = useState(false)
  const timer = useRef<ReturnType<typeof setInterval> | null>(null)

  const next = useCallback(() => setIndex(i => (i + 1) % TESTIMONIALS.length), [])
  const prev = useCallback(
    () => setIndex(i => (i - 1 + TESTIMONIALS.length) % TESTIMONIALS.length),
    [],
  )

  useEffect(() => {
    if (paused) return
    timer.current = setInterval(next, AUTOPLAY_MS)
    return () => {
      if (timer.current) clearInterval(timer.current)
    }
  }, [paused, next])

  const t: Testimonial = TESTIMONIALS[index]!

  return (
    <section
      className="relative overflow-hidden bg-ink py-16 text-[#f0e9dc] md:py-24 dark:bg-[#0d1b30]"
      aria-labelledby="testimonials-heading"
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
    >
      {/* faint ornamental background initials */}
      <span
        aria-hidden="true"
        className="pointer-events-none absolute -top-10 left-1/2 -translate-x-1/2 select-none font-display text-[16rem] leading-none text-white/[0.04] md:text-[22rem]"
      >
        D
      </span>

      <div className="relative mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-60px' }}
          transition={{ duration: 0.65, ease: [0.22, 1, 0.36, 1] }}
          className="text-center"
        >
          <p className="eyebrow !text-gold-soft">Client Stories</p>
          <h2 id="testimonials-heading" className="mt-3 font-display text-3xl md:text-4xl">
            Words from the Circle
          </h2>
          <div className="diamond-divider mx-auto mt-5 max-w-xs" aria-hidden="true">
            <span className="gold-gradient-bg inline-block size-2 rotate-45 rounded-[2px]" />
          </div>
        </motion.div>

        {/* Quote */}
        <div className="relative mt-10 min-h-[340px] sm:min-h-[300px]">
          <AnimatePresence mode="wait">
            <motion.figure
              key={t.id}
              initial={{ opacity: 0, y: 24 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -16 }}
              transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
              className="flex flex-col items-center text-center"
              aria-live="polite"
            >
              <StarRow />
              <blockquote className="mt-6 font-display text-xl italic leading-relaxed text-[#f0e9dc] md:text-2xl">
                <span aria-hidden="true" className="text-gold">
                  &ldquo;
                </span>
                {t.quote}
                <span aria-hidden="true" className="text-gold">
                  &rdquo;
                </span>
              </blockquote>

              {typeof t.dealValueKes === 'number' && (
                <p className="mt-5 text-[11px] font-bold uppercase tracking-[0.22em] text-gold-soft">
                  Closed {formatDate(t.dateIso)} · {formatKes(t.dealValueKes, { compact: true })}
                </p>
              )}

              <figcaption className="mt-7 flex items-center gap-3.5">
                <Avatar className="size-14 ring-2 ring-gold/50">
                  <AvatarImage src={t.photo} alt={`Portrait of ${t.name}`} />
                  <AvatarFallback className="gold-gradient-bg font-display text-sm font-bold text-[#1f1810]">
                    {initialsFor(t.name)}
                  </AvatarFallback>
                </Avatar>
                <span className="text-left">
                  <span className="block font-display text-lg leading-tight text-white">
                    {t.name}
                  </span>
                  <span className="block text-xs text-[#f0e9dc]/60">
                    {t.role} · {t.location}
                  </span>
                </span>
              </figcaption>
            </motion.figure>
          </AnimatePresence>
        </div>

        {/* Controls — classic 01 / 06 pagination */}
        <div className="mt-10 flex items-center justify-center gap-6">
          <Button
            variant="outline"
            size="icon"
            onClick={prev}
            aria-label="Previous testimonial"
            className="size-11 rounded-full border-white/25 bg-transparent text-[#f0e9dc] hover:border-gold hover:bg-gold hover:text-[#1f1810]"
          >
            <ChevronLeft className="size-4" aria-hidden="true" />
          </Button>
          <p className="font-display text-sm tracking-[0.3em] text-[#f0e9dc]/70" aria-live="polite">
            <span className="text-gold">{String(index + 1).padStart(2, '0')}</span>
            {' / '}
            {String(TESTIMONIALS.length).padStart(2, '0')}
          </p>
          <Button
            variant="outline"
            size="icon"
            onClick={next}
            aria-label="Next testimonial"
            className="size-11 rounded-full border-white/25 bg-transparent text-[#f0e9dc] hover:border-gold hover:bg-gold hover:text-[#1f1810]"
          >
            <ChevronRight className="size-4" aria-hidden="true" />
          </Button>
        </div>

        {/* dots */}
        <div className="mt-5 flex items-center justify-center gap-2" aria-hidden="true">
          {TESTIMONIALS.map((item, i) => (
            <button
              key={item.id}
              type="button"
              tabIndex={-1}
              onClick={() => setIndex(i)}
              className={cn(
                'h-1.5 rounded-full transition-all',
                i === index ? 'w-6 bg-gold' : 'w-1.5 bg-white/25 hover:bg-white/50',
              )}
            />
          ))}
        </div>

        {/* CTA */}
        <div className="mt-10 text-center">
          <Button
            type="button"
            onClick={() => setView('valuation')}
            className="gold-gradient-bg min-h-[44px] rounded-full px-8 font-semibold text-[#1f1810] hover:opacity-90"
          >
            Become our next success story
            <ArrowRight className="size-4" aria-hidden="true" />
          </Button>
        </div>
      </div>
    </section>
  )
}

// src/lib/components/Testimonials.svelte
<script lang="ts">
	import { testimonials } from '$lib/data/testimonials';
	import { onMount, onDestroy } from 'svelte';

	let active = $state(0);
	let autoplay: ReturnType<typeof setInterval>;

	function next() {
		active = (active + 1) % testimonials.length;
	}

	function prev() {
		active = (active - 1 + testimonials.length) % testimonials.length;
	}

	function goTo(i: number) {
		active = i;
	}

	function startAutoplay() {
		stopAutoplay();
		autoplay = setInterval(next, 6000);
	}

	function stopAutoplay() {
		if (autoplay) clearInterval(autoplay);
	}

	const current = $derived(testimonials[active]);

	onMount(() => startAutoplay());
	onDestroy(() => stopAutoplay());
</script>

<svelte:head></svelte:head>

<section
	class="testimonials"
	onmouseenter={stopAutoplay}
	onmouseleave={startAutoplay}
	aria-label="Client testimonials"
>
	<div class="container">
		<div class="section-header">
			<h2>What Our Clients Say</h2>
			<p>Real stories from buyers, sellers, and tenants we’ve helped across Nairobi</p>
		</div>

		<div class="carousel" role="region" aria-roledescription="carousel">
			<button type="button" class="nav-btn prev" onclick={prev} aria-label="Previous testimonial">‹</button>

			{#key active}
				<div class="testimonial-card">
					<div class="stars" aria-label="{current.rating} out of 5 stars">
						{#each Array(5) as _, i}
							<span class="star" class:filled={i < current.rating}>★</span>
						{/each}
					</div>

					<blockquote class="quote">“{current.quote}”</blockquote>

					<div class="author">
						<img src={current.avatar} alt={current.name} class="avatar" loading="lazy" />
						<div class="author-info">
							<strong>{current.name}</strong>
							<span class="author-role">{current.role} · {current.location}</span>
							<span class="author-date">{current.date}</span>
						</div>
					</div>
				</div>
			{/key}

			<button type="button" class="nav-btn next" onclick={next} aria-label="Next testimonial">›</button>
		</div>

		<div class="dots" role="tablist">
			{#each testimonials as t, i}
				<button
					type="button"
					class="dot"
					class:active={i === active}
					onclick={() => goTo(i)}
					aria-label="Go to testimonial {i + 1}"
					aria-selected={i === active}
					role="tab"
				></button>
			{/each}
		</div>
	</div>
</section>

<style>
	.testimonials {
		background: linear-gradient(135deg, #1f1810 0%, #2d2418 100%);
		color: #fff;
		padding: 70px 0;
		position: relative;
		overflow: hidden;
	}

	.testimonials::before {
		content: '';
		position: absolute;
		top: -30%;
		left: -10%;
		width: 400px;
		height: 400px;
		background: radial-gradient(circle, rgba(212, 175, 55, 0.1), transparent 70%);
		border-radius: 50%;
	}

	.testimonials::after {
		content: '';
		position: absolute;
		bottom: -30%;
		right: -10%;
		width: 400px;
		height: 400px;
		background: radial-gradient(circle, rgba(212, 175, 55, 0.08), transparent 70%);
		border-radius: 50%;
	}

	.container {
		max-width: 900px;
		margin: 0 auto;
		padding: 0 20px;
		position: relative;
		z-index: 1;
	}

	.section-header {
		text-align: center;
		margin-bottom: 40px;
	}

	.section-header h2 {
		font-size: 2rem;
		margin: 0 0 8px;
	}

	.section-header p {
		color: rgba(255, 255, 255, 0.65);
		margin: 0;
	}

	.carousel {
		display: flex;
		align-items: center;
		gap: 20px;
	}

	.testimonial-card {
		flex: 1;
		background: rgba(255, 255, 255, 0.05);
		border: 1px solid rgba(255, 255, 255, 0.1);
		border-radius: 16px;
		padding: 36px;
		text-align: center;
		backdrop-filter: blur(8px);
		animation: card-in 0.4s ease;
	}

	@keyframes card-in {
		from { opacity: 0; transform: translateY(12px); }
		to { opacity: 1; transform: translateY(0); }
	}

	.stars {
		margin-bottom: 18px;
	}

	.star {
		font-size: 1.3rem;
		color: rgba(255, 255, 255, 0.2);
		margin: 0 1px;
	}

	.star.filled {
		color: #d4af37;
	}

	.quote {
		font-size: 1.15rem;
		line-height: 1.7;
		color: rgba(255, 255, 255, 0.92);
		margin: 0 0 24px;
		font-style: italic;
	}

	.author {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 14px;
	}

	.avatar {
		width: 56px;
		height: 56px;
		border-radius: 50%;
		object-fit: cover;
		border: 2px solid #d4af37;
	}

	.author-info {
		text-align: left;
		display: flex;
		flex-direction: column;
		gap: 2px;
	}

	.author-info strong {
		color: #fff;
		font-size: 1rem;
	}

	.author-role {
		color: rgba(255, 255, 255, 0.6);
		font-size: 0.82rem;
	}

	.author-date {
		color: rgba(255, 255, 255, 0.4);
		font-size: 0.75rem;
	}

	.nav-btn {
		flex-shrink: 0;
		width: 44px;
		height: 44px;
		border-radius: 50%;
		border: 1px solid rgba(255, 255, 255, 0.2);
		background: rgba(255, 255, 255, 0.05);
		color: #fff;
		font-size: 24px;
		cursor: pointer;
		transition: all 0.2s;
	}

	.nav-btn:hover {
		background: #d4af37;
		color: #1f1810;
		border-color: #d4af37;
		transform: scale(1.05);
	}

	.dots {
		display: flex;
		justify-content: center;
		gap: 8px;
		margin-top: 24px;
	}

	.dot {
		width: 10px;
		height: 10px;
		border-radius: 50%;
		border: none;
		background: rgba(255, 255, 255, 0.25);
		cursor: pointer;
		transition: all 0.25s;
		padding: 0;
	}

	.dot.active {
		background: #d4af37;
		width: 28px;
		border-radius: 5px;
	}

	@media (max-width: 600px) {
		.testimonial-card {
			padding: 24px 18px;
		}
		.quote {
			font-size: 1rem;
		}
		.nav-btn {
			width: 36px;
			height: 36px;
			font-size: 18px;
		}
		.author {
			flex-direction: column;
			text-align: center;
		}
		.author-info {
			text-align: center;
			align-items: center;
		}
	}
</style>
